tap homebrew/cask-fonts
install font-jetbrains-mono-nerd-font
install coreutils
install ctags
install direnv
install htop
install jq
install ssh-copy-id
install rg
install tig
install tree
install nvim
install fzf
install tmux
install entr
install bat
install gh
install pyenv
install starship
