install coreutils
install ctags
install direnv
install docker
install ec2-api-tools
install elasticsearch
install ffind
install fish
install fortune
install git
install gitslave
install google-perftools
install haskell-platform
install heroku-toolbelt
install hr
install htop-osx
install imagemagick
install irssi
install jq
install libusb
install maven
install mercurial
install mongodb
install multitail
install mysql
install node
install p11-kit
install phantomjs
install postgresql
install pv
install python
install qemu
install ranger
install rbenv
install reattach-to-user-namespace
install redis
install ruby-build
install s3cmd
install ssh-copy-id
install the_silver_searcher
install tig
install tmate
install tree
install vim
install watch
install wemux
install wget
