XDG_CURRENT_DESKTOP=sway
XDG_SESSION_TYPE=wayland
QT_WAYLAND_DISABLE_WINDOWDECORATION=1
QT_WAYLAND_FORCE_DPI=physical
QT_AUTO_SCREEN_SCALE_FACTOR=0
QT_WAYLAND_RECONNECT=1
SDL_VIDEODRIVER=wayland
CLUTTER_BACKEND=wayland
ELECTRON_OZONE_PLATFORM_HINT=wayland
# this is for sway-desktop-launcher to be able to run cli apps
TERMINAL_COMMAND=kitty
